apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: botinfo
  name: botinfo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: botinfo
  template:
    metadata:
      labels:
        app: botinfo
    spec:
      containers:
        - args:
            - --stderrthreshold=0
          env:
            - name: GITEE_OAUTH2_SECRET
              valueFrom:
                secretKeyRef:
                  name: bot-secret
                  key: gitee_oauth2_secret
            - name: GITEE_OAUTH2_CLIENT_CODE
              valueFrom:
                secretKeyRef:
                  name: bot-secret
                  key: gitee_oauth2_client_code
            - name: WEBSITE_URL
              value: https://openeuler.org/
          image: swr.cn-south-1.myhuaweicloud.com/openeuler/bot:v1.0.202004301112269510
          imagePullPolicy: IfNotPresent
          name: botpod
          ports:
            - containerPort: 8888
              name: http
              protocol: TCP
          volumeMounts:
            - mountPath: /bot/config.yaml
              name: configmap-volume
              subPath: config.yaml
            - mountPath: /bot/_service
              name: bot-service-configmap
              subPath: _service
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: bot-configmap
          name: configmap-volume
        - configMap:
            defaultMode: 420
            name: bot-service-configmap
          name: bot-service-configmap